class CarData {
  static const Map<String, List<String>> carModels = {
    'Acura': ['ILX', 'MDX', 'NSX', 'RDX', 'RLX', 'TLX'],
    'Alfa Romeo': ['Giulia', 'Stelvio'],
    'Aston Martin': ['DB11', 'DBS', 'DBX', 'Vantage'],
    'Audi': ['A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'e-tron', 'Q3', 'Q5', 'Q7', 'Q8', 'R8', 'RS3', 'RS5', 'RS6', 'RS7', 'TT'],
    'BMW': ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '7 Series', '8 Series', 'i3', 'i8', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4'],
    'Bentley': ['Bentayga', 'Continental', 'Flying Spur'],
    'Bugatti': ['Chiron', 'Divo'],
    'Buick': ['Enclave', 'Encore', 'Envision'],
    'Cadillac': ['CT4', 'CT5', 'Escalade', 'XT4', 'XT5', 'XT6'],
    'Chevrolet': ['Blazer', 'Camaro', 'Colorado', 'Corvette', 'Equinox', 'Malibu', 'Silverado', 'Suburban', 'Tahoe', 'Traverse', 'Trax'],
    'Chrysler': ['300', 'Pacifica'],
    'Citroën': ['C1', 'C3', 'C3 Aircross', 'C4', 'C4 Cactus', 'C4 SpaceTourer', 'C5 Aircross', 'Berlingo'],
    'Dacia': ['Duster', 'Sandero', 'Logan', 'Lodgy'],
    'Dodge': ['Challenger', 'Charger', 'Durango', 'Journey'],
    'Ferrari': ['488', '812', 'F8', 'Portofino', 'Roma', 'SF90'],
    'Fiat': ['500', '500L', '500X', 'Panda', 'Tipo'],
    'Ford': ['EcoSport', 'Edge', 'Escape', 'Expedition', 'Explorer', 'F-150', 'Fiesta', 'Focus', 'Fusion', 'Mustang', 'Ranger', 'Transit'],
    'Genesis': ['G70', 'G80', 'G90', 'GV80'],
    'GMC': ['Acadia', 'Canyon', 'Sierra', 'Terrain', 'Yukon'],
    'Honda': ['Accord', 'Civic', 'CR-V', 'Fit', 'HR-V', 'Insight', 'Odyssey', 'Passport', 'Pilot', 'Ridgeline'],
    'Hyundai': ['Accent', 'Elantra', 'Ioniq', 'Kona', 'Palisade', 'Santa Fe', 'Sonata', 'Tucson', 'Veloster', 'Venue'],
    'Infiniti': ['Q50', 'Q60', 'QX50', 'QX60', 'QX80'],
    'Jaguar': ['E-Pace', 'F-Pace', 'F-Type', 'I-Pace', 'XE', 'XF', 'XJ'],
    'Jeep': ['Cherokee', 'Compass', 'Gladiator', 'Grand Cherokee', 'Renegade', 'Wrangler'],
    'Kia': ['Forte', 'K5', 'Niro', 'Optima', 'Rio', 'Seltos', 'Sorento', 'Soul', 'Sportage', 'Stinger', 'Telluride'],
    'Lamborghini': ['Aventador', 'Huracán', 'Urus'],
    'Land Rover': ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Evoque', 'Range Rover Sport', 'Range Rover Velar'],
    'Lexus': ['ES', 'GS', 'GX', 'IS', 'LC', 'LS', 'LX', 'NX', 'RC', 'RX', 'UX'],
    'Lincoln': ['Aviator', 'Continental', 'Corsair', 'Nautilus', 'Navigator'],
    'Lotus': ['Evora'],
    'Maserati': ['Ghibli', 'Levante', 'Quattroporte'],
    'Mazda': ['CX-3', 'CX-30', 'CX-5', 'CX-9', 'Mazda3', 'Mazda6', 'MX-5'],
    'McLaren': ['570S', '600LT', '720S', 'GT'],
    'Mercedes-Benz': ['A-Class', 'C-Class', 'CLA', 'CLS', 'E-Class', 'G-Class', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'S-Class', 'SL', 'SLC'],
    'MINI': ['Clubman', 'Countryman', 'Hardtop'],
    'Mitsubishi': ['Eclipse Cross', 'Mirage', 'Outlander', 'Outlander Sport'],
    'Nissan': ['370Z', 'Altima', 'Armada', 'Frontier', 'GT-R', 'Kicks', 'Leaf', 'Maxima', 'Murano', 'NV', 'Pathfinder', 'Rogue', 'Sentra', 'Titan', 'Versa'],
    'Opel': ['Astra', 'Corsa', 'Insignia', 'Mokka', 'Grandland X', 'Crossland X'],
    'Peugeot': ['108', '208', '308', '508', '2008', '3008', '5008'],
    'Porsche': ['718 Boxster', '718 Cayman', '911', 'Cayenne', 'Macan', 'Panamera', 'Taycan'],
    'Ram': ['1500', '2500', '3500'],
    'Renault': ['Clio', 'Captur', 'Megane', 'Kadjar', 'Zoe', 'Scenic', 'Twingo'],
    'Rolls-Royce': ['Cullinan', 'Dawn', 'Ghost', 'Phantom', 'Wraith'],
    'Skoda': ['Octavia', 'Fabia', 'Superb', 'Kodiaq', 'Karoq', 'Kamiq'],
    'Subaru': ['Ascent', 'BRZ', 'Crosstrek', 'Forester', 'Impreza', 'Legacy', 'Outback', 'WRX'],
    'Suzuki': ['Swift', 'Vitara', 'Jimny', 'Ignis', 'SX4 S-Cross'],
    'Tesla': ['Model 3', 'Model S', 'Model X', 'Model Y'],
    'Toyota': ['4Runner', '86', 'Avalon', 'Camry', 'C-HR', 'Corolla', 'Highlander', 'Land Cruiser', 'Prius', 'RAV4', 'Sequoia', 'Sienna', 'Supra', 'Tacoma', 'Tundra', 'Yaris'],
    'Volkswagen': ['Arteon', 'Atlas', 'Golf', 'ID.3', 'ID.4', 'Jetta', 'Passat', 'Polo', 'Tiguan', 'Touareg', 'T-Roc'],
    'Volvo': ['S60', 'S90', 'V60', 'V90', 'XC40', 'XC60', 'XC90'],
  };
}
